version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/code
    depends_on:
      - db
  
  db:
    image: postgis/postgis:15-3.3-alpine
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
      - data_postgres:/var/lib/postgres

volumes:
  data_postgres: